authentication/urls.py
from django.contrib import admin
from django.urls import path
from .views import VRegister, logout_session, login_session
from django.conf import settings
from django.conf.urls.static import static

app_name = "authentication"

urlpatterns = [
   
    path("register/", VRegister.as_view(), name="authentication"),
    path("login/", login_session, name="login"),
    path("logout/", logout_session, name="logout"),
    
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path, include
from. import views

urlpatterns = [
    path("", views.blog, name="blog"),
    path("category/<int:category_id>/", views.category, name="category"),
    
]

tiendaOnline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("services/", include("services.urls")),
    path("blog/", include("blog.urls")),
    path("contact/", include("contact.urls")),
    path("shop/", include("shop.urls")),
    path("cart/", include("shopcart.urls")),
    path("authentication/", include("authentication.urls")),
    path("orders/", include("orders.urls")),
    path("", include("tiendaOnlineApp.urls")),
    
]

tiendaOnlineApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.home, name="home"),
    
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tiendaOnlineApp/views.py
from django.shortcuts import render, HttpResponse
from services.models import Service
# Create your views here.

def home(request):
    return render(request, 'tiendaOnlineApp/home.html')

tiendaOnlineApp/templates/tiendaOnlineApp/base.html
<html>
    <head>
    {% load static %}



    <!-- Bootstrap -->
    <link href="{% static 'tiendaOnlineApp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

     <!-- Fonts -->
    
     <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
     <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
     

    <!-- Styles -->
    <link href="{% static 'tiendaOnlineApp/css/gestion.css'%}" rel="stylesheet">
</head>

<body>

    <h1 class="site-heading text-center text-white d-none d-lg-block">
      
        <span class="site-heading-lower">Gestión de Pedidos</span>
      </h1>
      <div style="text-align: right; margin-right: 100px; color:white;">
        {% if user.is_authenticated %}
          Hola {{user.username}}
          <a href="{% url 'authentication:logout' %}" style="color: white;">Cerrar sesión</a>
        {% else %}
          <a href="{% url 'authentication:login' %}" style="color: white;">Login</a> &nbsp; <a href="{% url 'authentication:authentication' %}" style="color: white;">Registrate</a>
        {% endif %}
      </div>


 <!-- Navbar -->
 <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
      <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="">Gestión de Pedidos</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item {% if request.path == '/' %} active {%endif%} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'home'%}">Inicio</a>
          </li>
          <li class="nav-item {% if request.path == '/services/' %} active {%endif%} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'services'%}">Servicios</a>
          </li>
          <li class="nav-item {% if request.path == '/shop/' %} active {%endif%} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'shop'%}">Tienda</a>
          </li>
          <li class="nav-item {% if request.path == '/contact/' %} active {%endif%}m px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'contact'%}">Contacto</a>
          </li>
          <li class="nav-item {% if request.path|slice:':6' == '/blog/' %} active {%endif%} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'blog'%}">Blog</a>
          </li>
         
        </ul>
      </div>
    </div>
  </nav>


  
    {% block content %}
    {% endblock %}

  
    {% block message %}
    {% endblock %}


    <!-- Footer -->
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0">
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	    </p>
        <p class="m-0 mbt">
        	<a href="sample.html" class="link">Política de privacidad</a> ·
        	<a href="sample.html" class="link">Aviso legal</a> ·
        	<a href="sample.html" class="link">Cookies</a>
		</p>
        <p class="m-0 mbt1">&copy; Gestión de Pedidos 2020</p>
      </div>
	</footer>

    <!-- Bootstrap -->
    <script src="{% static 'tiendaOnlineApp/vendor/jquery/jquery.min.js'%}"></script>
    <script src="{% static 'tiendaOnlineApp/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

</body>


</html>

tiendaOnlineApp/templates/tiendaOnlineApp/home.html
{% extends "tiendaOnlineApp/base.html" %}

{% load static %}

{% block content %}
   <!-- Heading -->
   <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'tiendaOnlineApp/img/principal.jpg'%}" alt="">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4" >
            <span class="section-heading-upper">Puntualidad</span>
            <span class="section-heading-lower">El mejor stock</span>
          </h2>
          <p class="mb-3">En la puertra de tu casa en menos de 48 h con el envío normal. En menos de 24 h con el envío express.
          </p>
         
        </div>
      </div>
    </div>
  </section>
{% endblock %}

{% block message %}
    <!-- Message -->
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-4">
                <span class="section-heading-upper">Compromiso total</span>
                <span class="section-heading-lower">Garantizado</span>
              </h2>
              <p class="mb-0">Con más de 75 años de experiencia a nuestras espaldas, desde Gestión de Pedidos tenemos los conocimientos y herramientas necesarios para llevar cualquier objeto a la puerta de su casa con puntualidad y profesionalidad.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    {% endblock %}

   