blog/urls.py
from django.urls import path, include
from. import views

urlpatterns = [
    path("", views.blog, name="blog"),
    path("category/<int:category_id>/", views.category, name="category"),
    
]

orders/urls.py
from django.urls import path, include
from. import views


app_name = "orders"
urlpatterns = [
    path("", views.process_order, name="order"),
    
]

shop/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.shop, name="shop"),
    
    
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shopcart/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "shopcart"

urlpatterns = [
    path("add/<int:product_id>", views.add_product, name="add"),
    path("delete/<int:product_id>", views.delete_product, name="delete"),
    path("subtract/<int:product_id>", views.subtract_product, name="subtract"),
    path("clear/", views.clear_cart, name="clear"),
    
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tiendaOnline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("services/", include("services.urls")),
    path("blog/", include("blog.urls")),
    path("contact/", include("contact.urls")),
    path("shop/", include("shop.urls")),
    path("cart/", include("shopcart.urls")),
    path("authentication/", include("authentication.urls")),
    path("orders/", include("orders.urls")),
    path("", include("tiendaOnlineApp.urls")),
    
]

shop/models.py
from django.db import models

# Create your models here.

class ProductCategory(models.Model):
    name = models.CharField(max_length=50, verbose_name="Nombre")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización")

    class Meta:
        verbose_name = "Categoría de producto"
        verbose_name_plural = "Categorías de productos"

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name="Nombre")
    description = models.TextField(verbose_name="Descripción")
    image = models.ImageField(upload_to="products/", verbose_name="Imagen")
    price = models.FloatField(verbose_name="Precio")
    stock = models.IntegerField(verbose_name="Stock")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización")
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name="Categoría")

    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render

from shop.models import ProductCategory, Product

# Create your views here.


def shop(request):
    categories = ProductCategory.objects.all()
    products = Product.objects.all()
    return render(request, 'shop/shop.html', {'categories': categories, 'products': products})

shop/templates/cart/widget.html
<table class="table table-bordered" style="color: white;">
    <thead>
        <tr>
            <th colspan="3" class="text-center">
                Carro de compras
            </th>
        </tr>
        <tr>
            <th>
                Producto
            </th>
            <th>
                Cantidad
            </th>
            <th>
                Suma
            </th>
        </tr>
    </thead>
    <tbody>
        {% if request.session.cart.items %}
            {% for key,value in request.session.cart.items %}
            <tr>
                <td>
                    {{value.product_name}}
                </td>
                <td>
                    {{value.quantity}}
                </td>
                
                <td>

                    <a href="{% url 'shopcart:add' value.product_id %}" class="btn btn-sm btn-success">
                        +
                    </a>

                    <a href="{% url 'shopcart:subtract' value.product_id %}" class="btn btn-sm btn-success">
                        -
                    </a>

                    {{value.price}}

                </td>
            </tr>
            {% endfor %}

        {% else %}

        <tr>
            <td colspan="3">
                <div class="alert alert-danger text-center">
                    Sin productos
                </div>
            </td>
            
        </tr>
        {% endif %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                Total: {{total_cost_cart}}
            </td>
        </tr>
        {% if  request.session.cart.items %}
        <tr>
            <td colspan="3" style="text-align: center;">
                <a href="{% url 'orders:order' %}" class="btn btn-success">Hacer pedido</a>
            </td>
        </tr>
        {% endif %}
    </tfoot>
</table>